### ISSUE TITLE
Use Accept-Language header instead of handcrafted label names

### ISSUE THREAD

**Issue by MorrisJobke** [opendatacity/re-data#26]
http://www.ietf.org/rfc/rfc2616.txt <- 14.4

It would be better to use the HTTP header to only specify the language you want the content in and not ship all languages, because this could become a lot of entries.

cc @phibos as he suggested this

**Comment by MorrisJobke** [comment]
@yetzt @toto @MichaelKreil Opinions?

**Comment by MorrisJobke** [comment]
This would also make the access to the correct element in an object more easy as you just need to get the value of `object[label]` instead of `object[label_de]`.

Then also the fallback from `de-DE` to `de` could be done on the server side and make the client code more robust/easier to maintain.

**Comment by MichaelKreil** [comment]
Hm,

I'm not satisfied with the current way of multi language support either. But manipulating HTTP Headers adds a lot of complexity. Especially on the server side. It's much harder to host the JSON files on your own Server, CDN or Github ...

What about multiple JSON files, like events_de.json, events_en.json?

Michael

**Comment by astro** [comment]
My opinion as an unaffiliated bystander: I think this is good because it reuses existing protocols for the purpose. Perhaps dropping internationalization is an acceptable drawback of using just static files.

**Comment by yetzt** [comment]
this can be handled by the webserver if a static file setup is used.

**Comment by MorrisJobke** [comment]
Then I would go for the HTTP header

**Comment by toto** [comment]
HTTP-Header still would leave out GitHub and CDNs, but I think it's still the best compromise.

**Comment by toto** [comment]
So for 0.2 we will use `Accept-Language` for localization.

**Comment by MorrisJobke** [comment]
:+1:

**Comment by yetzt** [comment]
\o/
