### ISSUE TITLE
Move specification to a separate repository/organisation

### ISSUE THREAD

**Issue by phibos** [opendatacity/re-data#27]
At the moment the specification looks like an api documentation for the tools hosted in the same repository.

To get the specification used be other developers/users it should be moved to a separate repository/organisation. It might also be a good idea to host the latest specification on a github page.

The "[TLS 1.3 Draft](https://github.com/tlswg/tls13-spec)" is an example for a specification hosted on github.

**Comment by toto** [comment]
Yep. @yetzt could you setup a ODC repo once we finish the discussion in #28

**Comment by yetzt** [comment]
ocd you mean. :)
unfortunately, [ocd](https://github.com/ocd) ist taken, but we'll think of something.

**Comment by phibos** [comment]
Do we still need this issue or can we close it?

**Comment by phibos** [comment]
Closing issue.
