### ISSUE TITLE
Find a name for the specification

### ISSUE THREAD

**Issue by phibos** [opendatacity/re-data#28]
The specification should get a name. It is much easier to talk/write about something if it has a name.

Something like "OEDF" - "Open Event Data Format"

**Comment by yetzt** [comment]
we were talking about that and came up with "open conference data", which woul be ocd.

**Comment by toto** [comment]
:+1: for OCD

**Comment by phibos** [comment]
Do we still need this issue or can we close it?

**Comment by phibos** [comment]
Closing issue.

**Comment by yetzt** [comment]
there has been this repo forever https://github.com/ocdata/re-data
