### ISSUE TITLE
multi-language support + default value

### ISSUE THREAD

**Issue by MichaelKreil** [opendatacity/re-data#31]
two entries per label:

``` javascript
label: "Deutsche Version",
label_translated: {
   "de": "Deutsche Version",
   "en": "English Version"
}
```

**Comment by yetzt** [comment]
i'd consider 
``` javascript
{
   "label": "Deutsche Version",
   "not": "translated",
   "different": {
      "item": "Text",
      "strings": "Whatever"
   },
   "_i18n": {
      "en": {
         "label": "English Version",
         "different.item": "Text"
      },
      "de": {
         "different.strings": "Wasauchimmer"
      }
   }
}
```

**Comment by championswimmer** [comment]
I would concurr here that label_xx approach is not very scalable if it goes beyond 2-3 languages. 

Also have you considered using a URL parameter such as ?locale=de to return de strings wherever possible and falling back to English else where ? 
This will make total data transferred over the JSON smaller, and enable having partial translations in some languages.
